image: maven:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - cd Spring-Boot-Project/1717
        - mvn clean compile

test:
    stage: test
    script:
        - cd Spring-Boot-Project/1717
        - mvn clean test
